export interface IEEERegion {
  id: string
  name: string
  sections: string[]
}

export const IEEE_MEMBERSHIP_GRADES = [
  'Student Member',
  'Graduate Student Member',
  'Member',
  'Senior Member',
  'Fellow',
  'Honorary Member',
  'Life Member',
] as const

export const IEEE_REGIONS: IEEERegion[] = [
  {
    id: 'region-1',
    name: 'Region 1 — Northeastern USA',
    sections: [
      'Berkshire',
      'Binghamton',
      'Boston',
      'Buffalo',
      'Connecticut',
      'Green Mountain',
      'Ithaca',
      'Long Island',
      'Maine',
      'Mid-Hudson',
      'Mohawk Valley',
      'New Hampshire',
      'New Jersey Coast',
      'New York',
      'North Jersey',
      'Princeton/Central Jersey',
      'Providence',
      'Rochester',
      'Schenectady',
      'Springfield',
      'Syracuse',
      'Worcester County',
    ],
  },
  {
    id: 'region-2',
    name: 'Region 2 — Eastern USA',
    sections: [
      'Akron',
      'Baltimore',
      'Central Pennsylvania',
      'Cincinnati',
      'Cleveland',
      'Columbus',
      'Dayton',
      'Delaware Bay',
      'Erie',
      'Johnstown',
      'Lehigh Valley',
      'Lima',
      'Northern Virginia',
      'Philadelphia',
      'Pittsburgh',
      'Southern New Jersey',
      'Susquehanna',
      'Washington',
      'West Virginia',
      'Youngstown',
    ],
  },
  {
    id: 'region-3',
    name: 'Region 3 — Southeastern USA',
    sections: [
      'Alabama',
      'Atlanta',
      'Central Georgia',
      'Central North Carolina',
      'Central Savannah River',
      'Central Tennessee',
      'Central Virginia',
      'Chattanooga',
      'Charlotte',
      'Coastal South Carolina',
      'Columbia',
      'Daytona',
      'East Tennessee',
      'Eastern North Carolina',
      'Evansville-Owensboro',
      'Florida West Coast',
      'Hampton Roads',
      'Huntsville',
      'Jamaica',
      'Lexington',
      'Louisville',
      'Memphis',
      'Miami',
      'Mississippi',
      'Mobile',
      'Orlando',
      'Palm Beach',
      'Piedmont',
      'Richmond',
      'Savannah',
      'Tallahassee',
      'Tri Cities',
      'Virginia Mountain',
      'Western North Carolina',
      'Winston-Salem',
    ],
  },
  {
    id: 'region-4',
    name: 'Region 4 — Central USA',
    sections: [
      'Calumet',
      'Cedar Rapids',
      'Central Illinois',
      'Central Indiana',
      'Central Iowa',
      'Chicago',
      'Fort Wayne',
      'Iowa-Illinois',
      'Madison',
      'Milwaukee',
      'Nebraska',
      'Northeastern Michigan',
      'Northeastern Wisconsin',
      'Red River Valley',
      'Rock River Valley',
      'Siouxland',
      'Southeastern Michigan',
      'Southern Minnesota',
      'Toledo',
      'Twin Cities',
      'West Michigan',
    ],
  },
  {
    id: 'region-5',
    name: 'Region 5 — Southwestern USA',
    sections: [
      'Arkansas',
      'Arkansas River Valley',
      'Baton Rouge',
      'Beaumont',
      'Central Texas',
      'Corpus Christi',
      'Dallas',
      'Denver',
      'El Paso',
      'Fort Worth',
      'Galveston Bay',
      'High Plains',
      'Houston',
      'Kansas City',
      'Lafayette',
      'Lone Star',
      'New Orleans',
      'Oklahoma City',
      'Ozark',
      'Panhandle',
      'Pikes Peak',
      'Saint Louis',
      'Shreveport',
      'South Plains',
      'Southwest Missouri',
      'Tulsa',
      'Wichita',
    ],
  },
  {
    id: 'region-6',
    name: 'Region 6 — Western USA',
    sections: [
      'Alaska',
      'Alamagordo-Holloman',
      'Albuquerque',
      'Boise',
      'Buenaventura',
      'Central Coast',
      'Central Montana',
      'Central Washington',
      'China Lake-Bakersfield',
      'Coastal Los Angeles',
      'Eastern Idaho',
      'Eastern Montana',
      'Foothill',
      'Ft. Huachuca',
      'Hawaii',
      'LANNM',
      'Las Vegas',
      'Metropolitan Los Angeles',
      'Northern Nevada',
      'Oakland-East Bay',
      'Oregon',
      'Orange County',
      'Palouse',
      'Phoenix',
      'Richland',
      'Sacramento Valley',
      'San Diego',
      'San Fernando Valley',
      'San Francisco',
      'Santa Clara Valley',
      'Seattle',
      'Spokane',
      'Tucson',
      'Utah',
      'Western Montana',
    ],
  },
  {
    id: 'region-7',
    name: 'Region 7 — Canada',
    sections: [
      'Canadian Atlantic',
      'Hamilton',
      'Kingston',
      'Kitchener-Waterloo',
      'London',
      'Montreal',
      'New Brunswick',
      'Newfoundland & Labrador',
      'North Saskatchewan',
      'Northern Canada',
      'Ottawa',
      'Peterborough',
      'Quebec',
      'Saint Maurice',
      'South Saskatchewan',
      'Southern Alberta',
      'Toronto',
      'Vancouver',
      'Victoria',
      'Windsor',
      'Winnipeg',
    ],
  },
  {
    id: 'region-8',
    name: 'Region 8 — Europe, Middle East & Africa',
    sections: [
      'Algeria',
      'Austria',
      'Bahrain',
      'Belarus',
      'Benelux',
      'Bosnia and Herzegovina',
      'Bulgaria',
      'Croatia',
      'Cyprus',
      'Czechoslovakia',
      'Denmark',
      'Egypt',
      'Estonia',
      'Finland',
      'France',
      'Germany',
      'Ghana',
      'Greece',
      'Hungary',
      'Iceland',
      'Iran',
      'Iraq',
      'Israel',
      'Italy',
      'Jordan',
      'Kazakhstan',
      'Kenya',
      'Kuwait',
      'Latvia',
      'Lebanon',
      'Lithuania',
      'Malta',
      'Mauritius',
      'Morocco',
      'Nigeria',
      'North Macedonia',
      'Norway',
      'Oman',
      'Poland',
      'Portugal',
      'Qatar',
      'Romania',
      'Russia',
      'Russia Northwest',
      'Russia Siberia',
      'Saudi Arabia East',
      'Serbia and Montenegro',
      'Slovenia',
      'South Africa',
      'Spain',
      'Sweden',
      'Switzerland',
      'Tunisia',
      'Turkey',
      'Uganda',
      'Ukraine',
      'United Kingdom and Ireland',
      'Western Saudi Arabia',
      'Zambia',
    ],
  },
  {
    id: 'region-9',
    name: 'Region 9 — Latin America & Caribbean',
    sections: [
      'Aguascalientes',
      'Bolivia',
      'Central West',
      'Centro Norte Brazil',
      'Colombia',
      'Colombia Caribbean',
      'Costa Rica',
      'Ecuador',
      'El Salvador',
      'Guatemala',
      'Guanajuato',
      'Guadalajara',
      'Honduras',
      'Mexico',
      'Minas Gerais',
      'Monterrey',
      'Morelos',
      'Nicaragua',
      'Northeast Brazil (Bahia)',
      'Panamá',
      'Peru',
      'Puebla',
      'Querétaro',
      'Rio de Janeiro',
      'South Brazil',
      'Trinidad & Tobago',
      'Puerto Rico & Caribe',
      'Puerto Rico West',
      'Venezuela',
      'Veracruz',
    ],
  },
  {
    id: 'region-10',
    name: 'Region 10 — Asia & Pacific',
    sections: [
      'Australia Capital Territory',
      'New South Wales',
      'Northern Australia',
      'Queensland',
      'South Australia',
      'Victorian',
      'Western Australia',
      'Bangladesh',
      'Beijing',
      'Chengdu',
      'Guangzhou',
      'Harbin',
      'Nanjing',
      'Shanghai',
      'Wuhan',
      'Xian',
      'Bangalore',
      'Bhubaneswar',
      'Delhi',
      'Gujarat',
      'Hyderabad',
      'Kerala',
      'Kharagpur',
      'Kolkata',
      'Madras',
      'Madhya Pradesh',
      'Maharashtra',
      'Pune',
      'Uttar Pradesh',
      'Vizag Bay',
      'Fukuoka',
      'Hiroshima',
      'Kansai',
      'Nagoya',
      'Sapporo',
      'Sendai',
      'Shikoku',
      'Shin-etsu',
      'Tokyo',
      'Busan',
      'Daejeon',
      'Gwangju',
      'Seoul',
      'Taegu',
      'Hong Kong',
      'Indonesia',
      'Macau',
      'Malaysia',
      'Nepal',
      'New Zealand Central',
      'New Zealand North',
      'New Zealand South',
      'Pakistan — Islamabad',
      'Pakistan — Karachi',
      'Pakistan — Lahore',
      'Philippines',
      'Singapore',
      'Sri Lanka',
      'Taiwan — Tainan',
      'Taiwan — Taipei',
      'Thailand',
      'Vietnam',
    ],
  },
]
